"""Scripted demo scenario constants."""

from __future__ import annotations

from app.constants import DEMO_BASELINE_WORLD_STATE, DEMO_SCENARIO_NAME, DEMO_SCENARIO_RUN_ID


DEFAULT_TICK_SECONDS = 1
SCENARIO_NAME = DEMO_SCENARIO_NAME
SCENARIO_RUN_ID = DEMO_SCENARIO_RUN_ID
INITIAL_STATE = DEMO_BASELINE_WORLD_STATE
