from __future__ import annotations

from .models import CandidateAction, ClusterState, DomainRisk, RiskForecast


def generate_candidate_actions(
    cluster: ClusterState,
    domain_risks: list[DomainRisk],
    forecast: RiskForecast,
) -> list[CandidateAction]:
    scenario = cluster.scenario_id
    policy_text = " ".join(cluster.policy_notes).lower()
    cooling_blocked = "cooling unit" in policy_text or "avoid cooling" in policy_text

    if scenario in {"cascade", "override_learning"}:
        actions = [
            CandidateAction(
                action_id="act-cascade-bundle",
                action_type="wait_for_checkpoint_then_migrate",
                title="Wait for checkpoint, migrate J-184 to R-7, cordon R-3, cap power",
                description="Preserve high-priority training while removing low-priority load from the degrading rack.",
                target_rack="R-3",
                target_node="R-3/N-2",
                target_job="J-184",
                destination_rack="R-7",
                prerequisites=["J-104 checkpoint safe window reached", "R-7 has four spare GPU slots"],
                estimated_risk_reduction=43,
                estimated_sla_impact="Improves p95 latency by reducing pressure on R-3 and the R-3:R-4 link.",
                estimated_performance_cost="Low for J-184; no interruption to high-priority training.",
                estimated_migration_minutes=2.5,
                reversibility="partially_reversible",
                safety="high",
                downside="Temporary batch slowdown and lower peak clocks on R-3.",
                why_valid="It addresses heat, power, network, and queue pressure without killing critical work.",
            ),
            CandidateAction(
                action_id="act-cooling-boost",
                action_type="increase_cooling",
                title="Increase cooling in R-3 zone",
                description="Ask facilities automation to boost fan and coolant response.",
                target_rack="R-3",
                prerequisites=["Cooling unit available"],
                estimated_risk_reduction=18,
                estimated_sla_impact="No direct SLA impact.",
                estimated_performance_cost="Higher cooling power draw.",
                estimated_migration_minutes=None,
                reversibility="reversible",
                safety="medium",
                downside="Does not reduce queue, power, or network pressure.",
                blocked_by_operator_policy=cooling_blocked,
                why_valid="Cooling delay is contributing to the thermal slope.",
                why_not_valid="Operator policy marks cooling escalation unavailable." if cooling_blocked else None,
            ),
            CandidateAction(
                action_id="act-power-cap-only",
                action_type="power_cap",
                title="Apply temporary 8% power cap to R-3",
                description="Reduce power draw and thermal rise on R-3 without moving jobs.",
                target_rack="R-3",
                estimated_risk_reduction=22,
                estimated_sla_impact="May slow affected training and inference jobs.",
                estimated_performance_cost="Medium; reduced clocks on R-3.",
                reversibility="reversible",
                safety="medium",
                downside="Risk remains high because queue and network pressure continue.",
                why_valid="Power is one of the compounding signals.",
            ),
            CandidateAction(
                action_id="act-do-nothing",
                action_type="do_nothing_monitor",
                title="Monitor for five more minutes",
                description="Do not intervene yet.",
                target_rack="R-3",
                estimated_risk_reduction=0,
                estimated_sla_impact="No immediate disruption.",
                estimated_performance_cost="None.",
                reversibility="reversible",
                safety="low",
                downside="Projected incident risk continues rising.",
                why_valid="Only valid if risk remains below intervention threshold.",
                why_not_valid="Risk forecast is already high or critical.",
            ),
        ]
        return actions

    if scenario == "gpu_health":
        return [
            CandidateAction(
                action_id="act-quarantine-gpu",
                action_type="quarantine_gpu",
                title="Drain and quarantine R-5/N-2/GPU-3 after checkpoint",
                description="Let the medium-priority job checkpoint, then isolate the suspect GPU and reschedule.",
                target_rack="R-5",
                target_node="R-5/N-2",
                target_gpu="R-5/N-2/GPU-3",
                target_job="J-184",
                destination_rack="R-7",
                prerequisites=["Checkpoint ETA below 2 minutes", "R-7 has healthy capacity"],
                estimated_risk_reduction=48,
                estimated_sla_impact="No critical inference impact.",
                estimated_performance_cost="Medium for J-184 during reschedule.",
                estimated_migration_minutes=3,
                reversibility="partially_reversible",
                safety="high",
                downside="Reduces available GPU capacity until hardware is inspected.",
                why_valid="ECC and XID signals indicate rising job failure risk.",
            ),
            CandidateAction(
                action_id="act-drain-node",
                action_type="drain_node",
                title="Drain all of R-5/N-2",
                description="Remove the whole node from scheduling and migrate workloads.",
                target_rack="R-5",
                target_node="R-5/N-2",
                estimated_risk_reduction=52,
                estimated_sla_impact="Consumes more spare capacity than GPU quarantine.",
                estimated_performance_cost="High for colocated workloads.",
                estimated_migration_minutes=5,
                reversibility="partially_reversible",
                safety="medium",
                downside="Over-broad if only one GPU is suspect.",
                why_valid="Node drain is conservative when error locality is unclear.",
            ),
            CandidateAction(
                action_id="act-monitor-gpu",
                action_type="do_nothing_monitor",
                title="Monitor GPU for one more interval",
                description="Delay action and watch for additional XID or ECC increase.",
                target_gpu="R-5/N-2/GPU-3",
                estimated_risk_reduction=0,
                estimated_sla_impact="No disruption.",
                estimated_performance_cost="None.",
                reversibility="reversible",
                safety="low",
                downside="The job could fail before the next checkpoint.",
                why_valid="Only valid for early watch-level anomalies.",
                why_not_valid="Health risk is trending high.",
            ),
        ]

    return [
        CandidateAction(
            action_id="act-scale-inference",
            action_type="preempt_batch_for_inference",
            title="Pause J-331 and scale inference replicas on R-8",
            description="Free low-priority batch GPUs and add inference capacity away from saturated queues.",
            target_rack="R-7",
            target_job="J-331",
            destination_rack="R-8",
            prerequisites=["R-8 has six free healthy GPU slots", "J-331 is preemptible"],
            estimated_risk_reduction=46,
            estimated_sla_impact="Improves p95 and p99 latency; protects critical inference.",
            estimated_performance_cost="Low-priority batch is delayed.",
            estimated_migration_minutes=2,
            reversibility="reversible",
            safety="high",
            downside="Offline eval completes later.",
            why_valid="Thermals are normal; the bottleneck is serving capacity and queue pressure.",
        ),
        CandidateAction(
            action_id="act-delay-batch",
            action_type="delay_new_placements",
            title="Delay new batch placements",
            description="Stop adding batch work until queue pressure stabilizes.",
            estimated_risk_reduction=18,
            estimated_sla_impact="Prevents additional pressure but does not add serving capacity.",
            estimated_performance_cost="Batch backlog grows.",
            reversibility="reversible",
            safety="medium",
            downside="Insufficient alone if SLA breach ETA is short.",
            why_valid="Prevents the scheduler from worsening fragmentation.",
        ),
        CandidateAction(
            action_id="act-escalate-sla",
            action_type="escalate_to_engineer",
            title="Escalate to serving engineer",
            description="Human escalation without automatic capacity change.",
            estimated_risk_reduction=5,
            estimated_sla_impact="Slow response if breach ETA is under ten minutes.",
            estimated_performance_cost="None.",
            reversibility="reversible",
            safety="low",
            downside="Does not directly reduce queue depth.",
            why_valid="Useful if automated scaling is unavailable.",
        ),
    ]
